
CREATE DATABASE adress_db;
USE adress_db;

CREATE TABLE contact (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    adress VARCHAR(100) NOT NULL,
    phone VARCHAR(15)
);

SHOW TABLES;

DESCRIBE contact;